[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm i -g pnpm@9.0.0", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node apps/api/dist/index.js"
