[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm i -g pnpm@9.0.0", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @repo/api build"]

[start]
cmd = "pnpm --filter @repo/api start"
